import Logo from './Logo.svg';
import BackButton from './BackButton.svg'
import Arrow from './Arrow.svg'
import Homescreen from './Homescreen.svg'
import Headline from './Headline.svg'
import Homelogo from './home1.svg'
import Orderlogo from './order1.svg'
import Profilelogo from './profile1.svg'
import User from './user.svg'
import Enter from './enter.svg'
import Ordermenu from './ordermenu.svg'
import Detailbutton from './detailbutton.svg'
import Card from './Card.png'
import Card2 from './Card2.png'
import Nominal from './nominal.svg'
import Unloadcard from './unloadcard.svg'
import Unloadcardbig from './unloadcardbig.svg'
export {Unloadcardbig, Nominal, Unloadcard,Card2,Card,Detailbutton,Ordermenu,Enter, Logo, BackButton, Arrow, Homescreen, Headline, Homelogo, Orderlogo, Profilelogo, User};